apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6.4-focal
        ports:
        - containerPort: 3306
        - containerPort: 33060
        envFrom:
          - configMapRef:
              name: db-cm
          - secretRef:
              name: db-pass
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: db-pvc
          mountPath: /var/lib/mysql
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - "-h"
            - "localhost"
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: db-pvc
          persistentVolumeClaim:
            claimName: db-pvc
