apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: wordpress-app
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi