apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wordpress-app
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: cGFzcw==

---
apiVersion: v1
kind: Secret
metadata:
  name: db-pass
  namespace: wordpress-app
type: Opaque
data:
  MYSQL_PASSWORD: cGFzcw==git 
  MYSQL_ROOT_PASSWORD: cGFzcw==


# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: gdrive-secret
#   namespace: wordpress-app
# type: Opaque
# stringData:
#   gdrive_folder_id: "${{ secrets.GDRIVE_FOLDER_ID }}"
#   gdrive_sa_json: '${{ secrets.GDRIVE_SA_JSON }}'